# Generated by Django 2.2.15 on 2020-10-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(max_length=100, verbose_name='Англ. название для ссылки')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name_plural': 'категории блога',
                'verbose_name': 'категория блога',
            },
        ),
    ]
