# Generated by Django 2.2.15 on 2020-11-21 14:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
