# Generated by Django 2.2.15 on 2020-08-29 18:31

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Документ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='blank',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='forms_blank_created_e3f9a3_brin'),
        ),
    ]
