# Generated by Django 2.2.15 on 2020-10-09 15:23

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200902_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blank',
            options={'ordering': ['order'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveIndex(
            model_name='blank',
            name='Шаблоны зая_created_280433_brin',
        ),
        migrations.AddField(
            model_name='blank',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='blank',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='forms_blank_created_e3f9a3_brin'),
        ),
        migrations.AlterModelTable(
            name='blank',
            table=None,
        ),
    ]
