# Generated by Django 2.2.15 on 2020-09-01 12:34

import django.contrib.postgres.indexes
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='friends/%Y/%m/%d/', verbose_name='Логотип')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на друга')),
            ],
            options={
                'verbose_name_plural': 'Дружественный проекты',
                'verbose_name': 'Дружественный проект',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='friend',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='friends_fri_created_abee9f_brin'),
        ),
    ]
