# Generated by Django 2.2.15 on 2020-08-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('movie_cat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieCategory',
            new_name='VideoCategory',
        ),
    ]
