# Generated by Django 2.2.15 on 2020-08-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_cat', '0002_auto_20200830_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='slug',
            field=models.CharField(default='', max_length=100, verbose_name='Англ. название для ссылки'),
            preserve_default=False,
        ),
    ]
