# Generated by Django 2.2.15 on 2020-08-29 15:16

import ckeditor_uploader.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='Английский аналог для вставки в ссылку')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='proects/proects')),
            ],
            options={
                'verbose_name': 'проект',
                'ordering': ['-created'],
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.AddIndex(
            model_name='proect',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='proects_pro_created_f7fa12_brin'),
        ),
    ]
