# Generated by Django 2.2.15 on 2020-08-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proect',
            options={'ordering': ['-created'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
